### ISSUE TITLE
Fix systemd init script to launch ns-3 w/o requiring an intermediate script

### ISSUE THREAD

**Issue by antonroman** [antonroman/dockemu-ansible#2]
Try to avoid the use of this script:

```
 # I didn't manage to get NS3 running directly from systemd script, this scriptis just used from systemd  
     - name: create launch NS3 script
       tags:
             - prepare
             - execute
       template:
           src: templates/launch_ns3.j2
           dest: "{{ deployFolder }}/{{ nsVersion }}/{{ nsCodeFolder }}/launch_ns3.sh"
           owner: dockemu
           #group: dockemu
           mode: 0755

```
